#!/bin/bash
yum -y install net-tools epel-release deltarpm 
yum -y install firewalld
chkconfig firewalld on
service firewalld restart
sleep 5
sed -i 's/#Port 22/Port 1022/g' /etc/ssh/sshd_config
firewall-cmd --zone=trusted --permanent --add-source=52.41.52.34
firewall-cmd --zone=trusted --permanent --add-source=52.8.201.128
firewall-cmd --zone=trusted --permanent --add-source=52.60.138.31
firewall-cmd --zone=trusted --permanent --add-source=50.17.48.216
firewall-cmd --zone=trusted --permanent --add-source=35.156.192.164
firewall-cmd --zone=trusted --permanent --add-source=34.209.216.231
firewall-cmd --zone=trusted --permanent --add-source=52.8.194.208
firewall-cmd --zone=trusted --permanent --add-source=34.200.114.108
firewall-cmd --zone=trusted --permanent --add-source=52.14.37.123
firewall-cmd --zone=trusted --permanent --add-source=52.32.223.28
firewall-cmd --zone=trusted --permanent --add-source=52.4.178.107
firewall-cmd --zone=public --permanent --remove-service=ssh
firewall-cmd --zone=public --permanent --remove-service=http
firewall-cmd --zone=public --permanent --add-port=10022/tcp
sleep 5
service sshd restart
sleep 5
firewall-cmd --reload
